tasks:
 
  - name: terraform
    before: |
      cd $PROJECT_ROOT  
      source ./bin/install_terraform_cli
      source ./bin/generate_tfrc_credentials
      source ./bin/set_tf_alias
      cp $PROJECT_ROOT/terraform.tfvars.example $PROJECT_ROOT/terraform.tfvars
  - name: sinatra
    before: | 
      cd $PROJECT_ROOT || exit 1  # Exit if $PROJECT_ROOT is not set or invalid
      gem install bundler        # Install Bundler if it's not already installed
      bundle install            # Install gems specified in Gemfile
      bundle exec ruby server.rb 
      cd terratowns_mock_server
  - name: aws-cli
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    before: |
      cd $PROJECT_ROOT
      source ./bin/set_tf_alias
      source ./bin/install_aws_cli
vscode:
  extensions:
    - amazonwebservices.aws-toolkit-vscode
    - hashicorp.terraform